<h2> Content List </h2>
<?php foreach($this->contents as $row) :  ?>
 	<div class="post">
			<h2 class="title"><a href="#"> <?php echo $row->title; ?> </a></h2>
			<p class="meta"><span class="date"> <?php echo date("M d, Y",strtotime($row->published)) ; ?> </span>
				<span class="posted">Posted by <a href="#"> <?php echo $row->author ; ?></a></span></p>
			<div style="clear: both;">&nbsp;</div>
			<div class="entry">
				<p> <?php echo $row->body ; ?></p>
				<p class="links"><a href="<?php echo $this->url(array('controller'=>'index','action'=>'page','id'=>$row->id),'pages');?>">Read More</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Comments</a></p>
			</div>
		</div>
	<div style="clear: both;">&nbsp;</div>
<?php endforeach; ?> 